# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 26 Oct 2021 12:46:49 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

zouhair:$2y$10$a9FXj74lVaP8Xld6ktAKd.lzokiQw7ZIkljxg0MHKYPjryHnQZBuO:Zouhair Ijaad:zouh.ijd@gmail.com:admin,user
